"""empty message

Revision ID: 01de005ea506
Revises: af83f96ee6c1
Create Date: 2024-05-20 18:03:56.933412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01de005ea506'
down_revision = 'af83f96ee6c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('novels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('synopsis', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('novels', schema=None) as batch_op:
        batch_op.drop_column('synopsis')

    # ### end Alembic commands ###
