"""remove 

Revision ID: af83f96ee6c1
Revises: 62cae62880ba
Create Date: 2024-05-15 17:43:11.561862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af83f96ee6c1'
down_revision = '62cae62880ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('novels', schema=None) as batch_op:
        batch_op.drop_column('novel_new_title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('novels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('novel_new_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
