"""add

Revision ID: e562f5d2530f
Revises: fd49d50e5e45
Create Date: 2024-05-15 12:32:51.035540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e562f5d2530f'
down_revision = 'fd49d50e5e45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('novels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_chapter', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('novels', schema=None) as batch_op:
        batch_op.drop_column('last_chapter')

    # ### end Alembic commands ###
