"""Initialize

Revision ID: fd49d50e5e45
Revises: 
Create Date: 2024-05-14 10:56:40.140543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd49d50e5e45'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('novels',
    sa.Column('novel_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('novel_new_title', sa.String(length=255), nullable=True),
    sa.Column('genre', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('novel_id')
    )
    op.create_table('chapters',
    sa.Column('chapter_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.novel_id'], ),
    sa.PrimaryKeyConstraint('chapter_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chapters')
    op.drop_table('novels')
    # ### end Alembic commands ###
